server:
    servlet:
      context-path: /auditing-api

spring:
  application:
    name: demo

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/xcauditing"
    username: "postgres"
    password: ""

  jpa:
    hibernate:
      ddl-auto: none


  flyway:
    enabled: true
    table: xc_flyway_schema_history
    locations: classpath:db/migration
    clean-disabled: true
    baseline-on-migrate: true

  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    property-naming-strategy: SNAKE_CASE
    time-zone: GMT+8
    deserialization:
      fail_on_unknown_properties: false

logging:
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss}){yellow} %clr(%-5level) [%thread] %clr(%logger{36}){blue} - %msg%n"

llm:
  provider:
    coze:
      app-id: 1185261263158
      apikey: sat_lHVT8MBuo0hC71uO5r6BtuW8zbJES1gmWUprWX4Lfq4Qli6fEpThfmrHSAOWXSWT
